### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by ArnCarveris** [clibequilibrium/EquilibriumEngine#4]
Hi.

Why it GPL but not MIT? it is big no no, it not possible get permission to use this engine in commercial project, I suggest change it, bc it scares a lot of potential contributors.

**Comment by clibequilibrium** [comment]
> Hi.
> 
> 
> 
> Why it GPL but not MIT? it is big no no, it not possible get permission to use this engine in commercial project, I suggest change it, bc it scares a lot of potential contributors.

Hi. Why not? 

GPL 2.0 perfectly allows for commercial use. Also Linux foundation software uses GPL 2.0 as well. Also if you are developing with GCC (which I did at the time) I had to license my software as GPL . 

I like the license because it encourages others people to contribute back if they choose to use it in their projects. 
If not, I do not mind they can still do private changes and state the changed only when they distribute binaries made with Equilibrium Engine,

I found this [article](https://fossa.com/blog/open-source-software-licenses-101-gpl-v2/) helpful 

Do you or your team has a need to have more permissive license?

**Comment by seemsindie** [comment]
Regarding GCC https://www.gnu.org/licenses/gcc-exception-3.1.en.html code compiled with it doesn't need to inherit the license.

**Comment by clibequilibrium** [comment]
> Regarding GCC https://www.gnu.org/licenses/gcc-exception-3.1.en.html code compiled with it doesn't need to inherit the license.

Thank you !

**Comment by clibequilibrium** [comment]
You may contact me for custom licensing at clibequilibrium@gmail.com, closing the ticket for now.
